version: '3.7'
services:
    db:
        image: 'postgres:11.2'
        container_name: 'chest_postgres1'
        ports:
            - '54321:5432'
        volumes:
            - postgres_data1:/var/lib/postgresql/data
volumes:
    postgres_data1:
        name: chest_postgres_data1
