const actions = {
    SET_ITEM_PROPERTY: 'SET_ITEM_PROPERTY',
    SUBMIT_ITEM_TO_INVENTORY: 'SUBMIT_ITEM_TO_INVENTORY',
    SUBMIT_ITEM_TO_INVENTORY_COMPLETE: 'SUBMIT_ITEM_TO_INVENTORY_COMPLETE',
    GET_ITEMS: 'GET_ITEMS',
    GET_ITEMS_COMPLETE: 'GET_ITEMS_COMPLETE',
};
export default actions;
