const actions = {
    SET_ITEM_PROPERTY: 'SET_ITEM_PROPERTY',
    ADD_PHOTO: 'ADD_PHOTO',
    SUBMIT_ITEM_TO_INVENTORY: 'SUBMIT_ITEM_TO_INVENTORY',
    SUBMIT_ITEM_TO_INVENTORY_COMPLETE: 'SUBMIT_ITEM_TO_INVENTORY_COMPLETE',
    SEND_PHOTO: 'SEND_PHOTO',
    SEND_PHOTO_COMPLETE: 'SEND_PHOTO_COMPLETE',
    DELETE_ITEM: 'DELETE_ITEM',
    GET_ITEMS: 'GET_ITEMS',
    GET_ITEMS_COMPLETE: 'GET_ITEMS_COMPLETE',
    GET_ITEM_SINGLE: 'GET_ITEM_SINGLE',
    GET_ITEM_SINGLE_COMPLETE: 'GET_ITEM_SINGLE_COMPLETE',
    LIST_ITEMS_PADDING_TOP: 'LIST_ITEMS_PADDING_TOP',
    CLEAR_EDITOR_FIELDS: 'CLEAR_EDITOR_FIELDS',
    GET_LOCATIONS: 'GET_LOCATIONS',
    GET_LOCATIONS_COMPLETE: 'GET_LOCATIONS_COMPLETE',
};
export default actions;
